--- !ruby/object:Railsui::Configuration
application_name: Startup mission with Rails UI
support_email: support@example.com
theme: hound
colors:
  primary:
    '50': "#eef2ff"
    '100': "#e0e7ff"
    '200': "#c7d2fe"
    '300': "#a5b4fc"
    '400': "#818cf8"
    '500': "#6366f1"
    '600': "#4f46e5"
    '700': "#4338ca"
    '800': "#3730a3"
    '900': "#312e81"
    '950': "#1e1b4b"
  secondary:
    '50': "#f8fafc"
    '100': "#f1f5f9"
    '200': "#e2e8f0"
    '300': "#cbd5e1"
    '400': "#94a3b8"
    '500': "#64748b"
    '600': "#475569"
    '700': "#334155"
    '800': "#1e293b"
    '900': "#0f172a"
    '950': "#020617"
pages:
- about
- activity
- assignments
- billing
- calendar
- dashboard
- integrations
- message
- messages
- notifications
- people
- pricing
- profile
- project
- projects
- settings
- team
